### PR TITLE
Set up aquapointer docs

### LINKED ISSUE #4: Add documentation
Add documentation for aquapointer. This could go by steps:
- step 1: update readme, #3 
- step 2: add docstrings
- step 3: add a proper Sphinx documentation
- step 4: publish documentation on readthedocs

### PR DESCRIPTION
**Pull request by Misty-W**
Fixes #4 
- [x]  Add files generated from Sphinx quickstart
- [x]  Create `apidoc.rst`
- [x] Setup Read the Docs

### CODE REVIEW

**Comment by Misty-W** [comment]
@FarLab and @nathanshammah I started this PR for the initial documentation setup. 

Haven't yet figured out what's causing the warnings on each entry in the API-doc, 

> WARNING: autodoc: failed to import module 'aquapointer'; the following exception was raised:
> No module named 'aquapointer.analog'

**Comment by Misty-W** [comment]
Also added `.readthedocs.yaml` file, but maybe I missed modifying something in the template?

**Comment by FarLab** [comment]
@Misty-W Just created a RTD account (username: farlab) and connected it with my github account!

**Comment by Misty-W** [comment]
Functions are showing up in API-doc now 🥳 . Rendering could be better- maybe a similar styling to what we have in Mitiq would be nice.

Also, I'm almost certain the RTD failure is due to RTD looking at `main` which of course doesn't have an RTD yaml file, whereas this PR does. Should "fix itself" upon merging. Eventually might want to preview RTD on PRs but that could probably wait in favor of other

**Comment by nathanshammah** [comment]
Great @Misty-W! I still cannot generate them with `sphinx-build -b html source build`. Is this what you're using?

**Comment by Misty-W** [comment]
> Great @Misty-W! I still cannot generate them with `sphinx-build -b html source build`. Is this what you're using?

@nathanshammah I'm using `make html`.

**Comment by nathanshammah** [comment]
Mmh, strange, I get this message, even if I installed aquapointer with `pip install -e . ` (v.0.0.2):
```
WARNING: Failed to import aquapointer.
Possible hints:
* KeyError: 'aquapointer'
* ModuleNotFoundError: No module named 'scipy'
WARNING: Failed to import aquapointer.analog.
Possible hints:
* KeyError: 'aquapointer'
* ModuleNotFoundError: No module named 'scipy'
WARNING: Failed to import aquapointer.analog.analog.
Possible hints:
* KeyError: 'aquapointer'
* ModuleNotFoundError: No module named 'scipy'
WARNING: Failed to import aquapointer.analog.density_mapping.
Possible hints:
* KeyError: 'aquapointer'
* ModuleNotFoundError: No module named 'scipy'
WARNING: Failed to import aquapointer.analog.qubo_solution.
Possible hints:
* KeyError: 'aquapointer'
* ModuleNotFoundError: No module named 'scipy'
WARNING: Failed to import aquapointer.analog_digital.
Possible hints:
* KeyError: 'aquapointer'
* ModuleNotFoundError: No module named 'scipy'
WARNING: Failed to import aquapointer.digital.
Possible hints:
* KeyError: 'aquapointer'
* ModuleNotFoundError: No module named 'scipy'
WARNING: Failed to import aquapointer.slicing.
Possible hints:
* KeyError: 'aquapointer'
* ModuleNotFoundError: No module named 'scipy'
building [mo]: targets for 0 po files that are out of date
writing output...
building [html]: targets for 0 source files that are out of date
updating environment: 0 added, 1 changed, 0 removed
reading sources... [100%] apidoc
WARNING: autodoc: failed to import module 'aquapointer'; the following exception was raised:
No module named 'scipy'
WARNING: autodoc: failed to import module 'analog' from module 'aquapointer'; the following exception was raised:
No module named 'scipy'
WARNING: autodoc: failed to import module 'analog.analog' from module 'aquapointer'; the following exception was raised:
No module named 'scipy'
WARNING: autodoc: failed to import module 'analog.density_mapping' from module 'aquapointer'; the following exception was raised:
No module named 'scipy'
WARNING: autodoc: failed to import module 'analog.qubo_solution' from module 'aquapointer'; the following exception was raised:
No module named 'scipy'
WARNING: autodoc: failed to import module 'analog_digital' from module 'aquapointer'; the following exception was raised:
No module named 'scipy'
WARNING: autodoc: failed to import module 'digital' from module 'aquapointer'; the following exception was raised:
No module named 'scipy'
WARNING: autodoc: failed to import module 'slicing' from module 'aquapointer'; the following exception was raised:
No module named 'scipy'
WARNING: autodoc: failed to import class 'density_canvas' from module 'aquapointer'; the following exception was raised:
No module named 'scipy'
WARNING: autodoc: failed to import class 'analog_digital.processor' from module 'aquapointer'; the following exception was raised:
No module named 'scipy'
```

**Comment by Misty-W** [comment]
@nathanshammah I think `pip install -e ".[development]"` should resolve the environment issues. 

@FarLab, are you able to build and open the docs from this branch locally?

**Review by FarLab — APPROVED** [review]
LGTM

**Pull request merged**
