### PR TITLE
Script for automated workflow

### LINKED ISSUE #75: Script for automated workflow

### PR DESCRIPTION
**Pull request by Misty-W**
Fixes #75 and #77.

Create a script to 
- Load input files
- Call functions to slice the density and find the locations of water molecules
- Save the output

### CODE REVIEW

**Comment by DanieleQubit** [comment]
Testing docker + automated script for analog emulation: WIP

**Comment by Misty-W** [comment]
@DanieleQubit please make sure you update your clone to the latest commit on this branch, since I just reverted a change I made yesterday, experimenting with grid scaling in slicing.

**Comment by DanieleQubit** [comment]
Hi, here my first test, which results in a python error message (see later in this message):

1) 3DRISM density used attached here inside the .zip
[2a15_ph4.zip](https://github.com/user-attachments/files/16017945/2a15_ph4.zip)
2) the analog parameter file (in the zip too):

"7 7.3585242543498035 124.66370614359172 3000
10 30
poisson-disk 0 0 4 6 5
filter gaussian-laplace 0.5
crop 4.70 -12.0 5.0 5.0
2.702 -11.26 -9.197 3.202 -11.260 -9.197 2.702 -10.76 -9.197
2.702 -11.26 -9.697 3.202 -11.260 -9.697 2.702 -10.76 -9.697"

3) the automated flow .py modified is in the zip too.

I have this error:
Screenshot from 2024-06-27 18-13-00

in the same screenshot you can also see the command I used to run the simulation:
"docker exec aquapointer_test /bin/bash -c 'python ./aquapointer/analog/automated_flow.py'"

**Comment by DanieleQubit** [comment]
Second attempt, using this `analog_settings_example`:

`7 7.3585242543498035 124.66370614359172 3000
10 30
poisson-disk 0 0 4 6 5
filter gaussian-laplace 0.5
crop 2.735 -11.263 5.0 5.0
2.735 -33.513 -20.049 -12.835 -11.263 -20.049 -12.835 -33.513 -9.197
2.735 -33.513 -19.549 -12.835 -11.263 -19.549 -12.835 -33.513 -8.697
2.735 -33.513 -19.049 -12.835 -11.263 -19.049 -12.835 -33.513 -8.197`

but the error is same as with the previous one.

**Comment by DanieleQubit** [comment]
Latest test using this other input:

```
7 7.3585242543498035 124.66370614359172 3000
10 30
poisson-disk 0 0 4 6 5
filter gaussian-laplace 0.5
crop 2.735 -11.263 5.0 5.0
-12.835 -33.513 -9.197 -12.535 -33.513 -9.197 -12.535 -33.013 -9.197
-12.835 -33.513 -9.697 -12.535 -33.513 -9.697 -12.535 -33.013 -9.697
-12.835 -33.513 -10.197 -12.535 -33.513 -10.197 -12.535 -33.013 -10.197
```
still same error.

**Comment by Misty-W** [comment]
@DanieleQubit, I reproduced the error and was able to solve it by removing the empty lines at the end of the file. 
As a quick fix, I'll add a condition to avoid creation of slicing point arrays for empty lines. 
I say "quick fix" because I do realize the current setup isn't optimized yet for ease of use, robustness, etc. 

Once I cleared the error above, I discovered another error in slicing that I hadn't encountered with my test cases (including those from Mauro's bug report). 

> File "/Users/mistywahl/Documents/GitHub/aquapointer/aquapointer/slicing.py", line 217, in _shape_slice
    density_array = np.zeros((m, n))
UnboundLocalError: local variable 'm' referenced before assignment

Part of it is that m and n shouldn't be calculated every iteration, but also there seems to be something strange happening with the grid snapping. I'll keep debugging and post updates here.

**Comment by Misty-W** [comment]
@DanieleQubit @darcangelomauro I fixed the error Daniele reported and the one I subsequently encountered (ordering of the slicing planes), but now there are issues when creating the lattice from the density slices. 
The first and third examples from Daniele "hang" at the lattice creation step but run through without errors when I remove the cropping line from the settings file. On Daniele's second example (minus the cropping line), I get this error:
> Traceback (most recent call last):
>   File "/Users/mistywahl/Documents/GitHub/aquapointer/aquapointer/analog/automated_flow.py", line 6, in <module>
>     from aquapointer.slicing import density_file_to_grid, density_slices_by_planes
>   File "/Users/mistywahl/Documents/GitHub/aquapointer/aquapointer/__init__.py", line 8, in <module>
>     from aquapointer.analog import analog, automated_flow, density_mapping, qubo_solution, utils
>   File "/Users/mistywahl/Documents/GitHub/aquapointer/aquapointer/analog/automated_flow.py", line 132, in <module>
>     locations = rism_to_locations(
>   File "/Users/mistywahl/Documents/GitHub/aquapointer/aquapointer/analog/automated_flow.py", line 65, in rism_to_locations
>     [c.set_poisson_disk_lattice(spacing) for c in canvases]
>   File "/Users/mistywahl/Documents/GitHub/aquapointer/aquapointer/analog/automated_flow.py", line 65, in <listcomp>
>     [c.set_poisson_disk_lattice(spacing) for c in canvases]
>   File "/Users/mistywahl/Documents/GitHub/aquapointer/aquapointer/density_canvas/DensityCanvas.py", line 349, in set_poisson_disk_lattice
>     lattice = Lattice.poisson_disk(
>   File "/Users/mistywahl/Documents/GitHub/aquapointer/aquapointer/density_canvas/Lattice.py", line 135, in poisson_disk
>     ref_radius = radius_density[_index_from_position(ref_point)]
> IndexError: index 82 is out of bounds for axis 0 with size 79

**Review by FarLab — APPROVED** [review]

**Pull request merged**
